#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# (c) Antonio Sánchez León, 2018 <introlinux[fix@]gmail[fix.]com>
# (c) Miguel Anxo Bouzada, 2018 <mbouzada[fix@]gmail[fix.]com>
# (c) GALPon MinNo Team, 2018 <minino[fix@]galpon[fix.]org>

## -

## Mensajes según idioma
case $LANG in
	ca*)
		MSG0="ATENCIÓN:"
		MSG1="Para Usar este script necesita tener instalado «sysbench»
para solucionarlo, aplique en la terminal «apt install sysbench»"
		TIT="Valoración rápida"
		PUNT="Calificación de este ordenador:"
		TEXT0="\n\tEste equipo es <b>INSUFICIENTE</b> \n\tpara tareas cotidianas de hoy día."
		TEXT1="\n\tEste equipo es <b>MUY JUSTO</b> \n\tpara tareas cotidianas de hoy día."
		TEXT2="\n\tEste equipo es <b>SUFICIENTE</b> \n\tpara hacer de casi de todo pero \n\tun poco justo para algunas tareas."
		TEXT3="\n\tEste equipo está <b>BIEN</b> \n\tpara hacer de todo un poco, pero \n\tsin pedirle peras al olmo."
		TEXT4="\n\tEste equipo es <b>NOTABLE</b>, \n\tpodrá hacer prácticamente \n\tcualquier cosa con este ordenador."
		TEXT5="\n\tEste equipo es <b>SOBRESALIENTE</b>, \n\tpodrá hacer prácticamente cualquier \n\tcosa con este ordenador."
		TEXT6="\n\t<span size='large' color='red'><b>No fué posible evaluar este equipo</b></span>"
		;;
	es*)
		MSG0="ATENCIÓN:"
		MSG1="Para Usar este script necesita tener instalado «sysbench»
para solucionarlo, aplique en la terminal «apt install sysbench»"
		TIT="Valoración rápida"
		PUNT="Calificación de este ordenador:"
		TEXT0="\n\tEste equipo es <b>INSUFICIENTE</b> \n\tpara tareas cotidianas de hoy día."
		TEXT1="\n\tEste equipo es <b>MUY JUSTO</b> \n\tpara tareas cotidianas de hoy día."
		TEXT2="\n\tEste equipo es <b>SUFICIENTE</b> \n\tpara hacer de casi de todo pero \n\tun poco justo para algunas tareas."
		TEXT3="\n\tEste equipo está <b>BIEN</b> \n\tpara hacer de todo un poco, pero \n\tsin pedirle peras al olmo."
		TEXT4="\n\tEste equipo es <b>NOTABLE</b>, \n\tpodrá hacer prácticamente \n\tcualquier cosa con este ordenador."
		TEXT5="\n\tEste equipo es <b>SOBRESALIENTE</b>, \n\tpodrá hacer prácticamente cualquier \n\tcosa con este ordenador."
		TEXT6="\n\t<span size='large' color='red'><b>No fué posible evaluar este equipo</b></span>"
		;;
	gl*)
		MSG0="ATENCIÓN:"
		MSG1="Para Usar este script precisa ter instalado «sysbench»
para solucionalo, aplique na terminal «apt install sysbench»"
		TIT="Valoración rápida"
		PUNT="Cualificación deste computador:"
		TEXT0="\n\tEste equipo é <b>INSUFICIENTE</b> \n\tpara tarefas cotiás de hoxe en día"
		TEXT1="\n\tEste equipo é <b>MOI XUSTO</b> \n\tpara tarefas cotiás de hoxe en día."
		TEXT2="\n\tEste equipo é <b>SUFICIENTE</b> \n\tpara facer case de todo mais \n\tun chisco xusto para algunhas tarefas."
		TEXT3="\n\tEste equipo está <b>BEN</b> \n\tpara facer de todo un pouco, mais \n\tsen pedir o demo e a aña ."
		TEXT4="\n\tEste equipo é <b>NOTÁBEL</b>, \n\tcon este computador poderá facer \n\tpracticamente calquera cousa."
		TEXT5="\n\tEste equipo é <b>SOBRESAÍNTE</b>, \n\tcon este computador poderá facer \n\tpracticamente calquera cousa."
		TEXT6="\n\t<span size='large' color='red'><b>Non foi posíbel avaliar este equipo</b></span>"
		;;
	*)
		MSG0="ATENCIÓN:"
		MSG1="Para Usar este script necesita tener instalado «sysbench»
para solucionarlo, aplique en la terminal «apt install sysbench»"
		TIT="Valoración rápida"
		PUNT="Calificación de este ordenador:"
		TEXT0="\n\tEste equipo es <b>INSUFICIENTE</b> \n\tpara tareas cotidianas de hoy día."
		TEXT1="\n\tEste equipo es <b>MUY JUSTO</b> \n\tpara tareas cotidianas de hoy día."
		TEXT2="\n\tEste equipo es <b>SUFICIENTE</b> \n\tpara hacer de casi de todo pero \n\tun poco justo para algunas tareas."
		TEXT3="\n\tEste equipo está <b>BIEN</b> \n\tpara hacer de todo un poco, but \n\twithout asking for the moon."
		TEXT4="\n\tEste equipo es <b>NOTABLE</b>, \n\tpodrá hacer prácticamente \n\tcualquier cosa con este ordenador."
		TEXT5="\n\tEste equipo es <b>SOBRESALIENTE</b>, \n\tpodrá hacer prácticamente cualquier \n\tcosa con este ordenador."
		TEXT6="\n\t<span size='large' color='red'><b>No fué posible evaluar este equipo</b></span>"
		;;
esac


## Comprobamos si existe el ejecutable «sysbench»
FILE0=/usr/bin/sysbench
if [ ! -x ${FILE0} ]; then
	echo ""
	echo "${MSG0}"
    echo "${MSG1}"
	echo ""
	echo ""
	exit 0
fi

## Ejecutamos la orden base
EVENTOS=`sysbench --test=cpu --max-time=5 --num-threads=8 run|grep "total number of events"|awk '{print $5}'`

#NOTA=$(($EVENTOS/1000))
#NOTA=$(echo "scale=2; $EVENTOS/1000"|bc)
NOTA=`echo print ${EVENTOS}/1000. |python`
NOTASINDECIMALES=`echo print ${EVENTOS}/1000 |python`

## Asignamos el mensaje y el icono en función de la «nota»
case ${NOTASINDECIMALES} in
	0)
		VALORACION="${TEXT0}"
		FACE="face-sick"
		;;
	1)
		VALORACION="${TEXT0}"
		FACE="face-sick"
		;;
	2)
		VALORACION="${TEXT0}"
		FACE="face-worried"
		;;
	3)
		VALORACION="${TEXT0}"
		FACE="face-tired"
		;;
	4)
		VALORACION="${TEXT1}"
		FACE="face-uncertain"
		;;
	5)
		VALORACION="${TEXT2}"
		FACE="face-smirk"
		;;
	6) 
		VALORACION="${TEXT3}"
		FACE="face-smile"
		;;
	7)
		VALORACION="${TEXT4}"
		FACE="face-smile-big"
		;;
	8)
		VALORACION="${TEXT4}"
		FACE="face-smile-big"
		;;
	9)
		VALORACION="${TEXT5}"
		FACE="face-laugh"
		;;
	10) 
		VALORACION="${TEXT5}"
		FACE="face-laugh"
		;;
	*)
		VALORACION="${TEXT6}"
		FACE="face-angry"
		;;
esac


echo ${NOTA}

## Ventana con mensaje final en función del generador de ventanas existente en el sistema
FILE1=/usr/bin/yad
if [ "test -x ${FILE1}" ]; then
    yad --info \
		--window-icon="face-smile"\
		--image="${FACE}" \
		--title "Valoración rápida" \
		--text \
			"\n\tNota de este ordenador: <b>${NOTA}</b> 
			\t${VALORACION}"
else
    zenity --info \
		--title "Valoración rápida" \
		--text \
			"\n\tNota de este ordenador: <b>${NOTA}</b> 
			\t${VALORACION}"
fi

